version: '3.9'

services:

  client:
    build: ./client/shopping-app
    ports:
      - "3000:80"
    depends_on:
      - dotnet-api
      - node-api

  dotnet-api:
    build: ./server/server-dotnet
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sql;Database=CatalogDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    depends_on:
      - sql

  node-api:
    build: ./server/server-node
    ports:
      - "5001:5001"
    environment:
      - OPENSEARCH_NODE=http://opensearch:9200
    depends_on:
      - opensearch

  sql:
    build: ./sql-custom
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1'"]
      interval: 10s
      retries: 5
      start_period: 30s

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
